# Generated by Django 6.0.4 on 2026-05-07 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_goal_current_amount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
