# Generated by Django 6.0.4 on 2026-05-07 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_alter_budget_category'),
        ('transactions', '0008_merge_20260507_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.category'),
        ),
    ]
