# Generated by Django 6.0.4 on 2026-05-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_budget_current_budget_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='current',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
