# Generated by Django 6.0.4 on 2026-05-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('i', 'income'), ('e', 'expense')], max_length=15),
        ),
    ]
