# Generated by Django 6.0.4 on 2026-05-06 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_date_time'),
        ('transactions', '0003_merge_20260506_2332'),
    ]

    operations = [
    ]
