# Generated by Django 6.0.4 on 2026-05-06 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_type'),
        ('transactions', '0003_alter_transaction_date_time'),
    ]

    operations = [
    ]
