# Generated by Django 6.0.4 on 2026-05-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_remove_category_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('i', 'income'), ('e', 'expense')], default='e', max_length=1),
        ),
    ]
