# Generated by Django 6.0.4 on 2026-05-07 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_merge_20260506_2257'),
        ('transactions', '0007_merge_0004_merge_20260507_0006_0006_category_type'),
    ]

    operations = [
    ]
