# Generated by Django 6.0.4 on 2026-05-07 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_alter_transaction_date_time'),
        ('transactions', '0008_merge_20260507_1534'),
        ('transactions', '0009_alter_transaction_date_time'),
    ]

    operations = [
    ]
