# Generated by Django 6.0.4 on 2026-05-07 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_merge_20260507_2158'),
        ('transactions', '0010_merge_20260507_2339'),
    ]

    operations = [
    ]
